Modifications

diff --git a/install b/install
--- a/install
+++ b/install
@@ -41,9 +41,9 @@ if [ -d $NIMBUS_HOME ] && [ "$(ls -A $NIMBUS_HOME)" ]; then
         echo "The destination directory '$NIMBUS_HOME' exists and is not empty."
         echo "It is not recommended to reinstall Nimbus into an existing install."
         echo ""
-        echo "If you are making changes to the services, you can build and install those directly:"
+        echo "If you are making changes to the service code, you can build and install those directly:"
         echo "    export GLOBUS_LOCATION=$NIMBUS_HOME/services"
-        echo "    scripts/all-build-and-install.sh"
+        echo "    scripts/jars-build-and-install.sh"
         echo ""
         echo "If you know what you are doing and want to reinstall, edit this script:"
         echo "    $0"
@@ -54,6 +54,17 @@ if [ -d $NIMBUS_HOME ] && [ "$(ls -A $NIMBUS_HOME)" ]; then
     fi
 fi
 
+if [ "X$PYTHON" = "X" ]; then
+    PYTHON_EXE=`which python`
+else
+    PYTHON_EXE="$PYTHON"
+fi
+# returns 0 if Python 2.5+
+$PYTHON_EXE -c "import sys; sys.exit(sys.version_info < (2,5))"
+if [ $? -ne 0 ]; then
+    echo "ERROR: The central Nimbus node must have Python version 2.5 or later (VMM nodes can have 2.4+)."
+    exit 1
+fi
 
 if [ ! -d $NIMBUS_HOME ]; then
     mkdir $NIMBUS_HOME
@@ -71,18 +82,6 @@ chmod 600 $NIMBUS_HOME/install.log
 if [ $? -ne 0 ]; then
   echo "ERROR: cannot chmod install log file: $NIMBUS_HOME/install.log"
   exit 1
-fi
-
-if [ "X$PYTHON" = "X" ]; then
-    PYTHON_EXE=`which python`
-else
-    PYTHON_EXE="$PYTHON"
-fi
-# returns 0 if Python 2.5+
-$PYTHON_EXE -c "import sys; sys.exit(sys.version_info < (2,5))"
-if [ $? -ne 0 ]; then
-    echo "ERROR: The central Nimbus node must have Python version 2.5 or later (VMM nodes can have 2.4+)."
-    exit 1
 fi
 
 echo ""
@@ -115,6 +114,17 @@ if [ ! -f $CUMULUS_ENV ]; then
     exit 1
 fi
 
+export NIMBUS_HOME
+source $pyve_path/bin/activate
+export LANTORRENT_HOME=$NIMBUS_HOME/lantorrent
+
+$NIMBUS_SRC/lantorrent/install.sh $LANTORRENT_HOME | tee -a $NIMBUS_HOME/install.log
+rc=$PIPESTATUS
+if [ $rc -ne 0 ]; then
+    echo "lantorrent install failed"
+    exit $rc
+fi
+
 echo ""
 echo "-----------------------------------------------------------------"
 echo " Configuring installed services"
@@ -127,8 +137,44 @@ if [ ! -f $CONFIG_SCRIPT ]; then
     exit 1
 fi
 
-$CONFIG_SCRIPT
+vmm_cmd="Programmer. Error."
+EXTRA_CONFIG_SCRIPT_ARGS=""
+if [ "X" != "X$PREVIOUS_NIMBUS_HOME_VALIDATED" ]; then
+    echo ""
+    echo "Beginning the configuration with values from the old Nimbus installation: $PREVIOUS_NIMBUS_HOME_VALIDATED"
+    echo ""
+    
+    oldnimbusconf=$PREVIOUS_NIMBUS_HOME_VALIDATED/nimbus-setup.conf
+    if [ ! -f $oldnimbusconf ]; then
+        echo "The old Nimbus installation does not have a configuration file, expecting to find: $oldnimbusconf"
+        exit 1
+    fi
+    
+    cp $oldnimbusconf $NIMBUS_HOME/nimbus-setup.conf
+    if [ $? -ne 0 ]; then
+        echo "Could not copy the old configuration file: cp $oldnimbusconf $NIMBUS_HOME/nimbus-setup.conf"
+        exit 1
+    fi
+    
+    EXTRA_CONFIG_SCRIPT_ARGS="--conf $NIMBUS_HOME/nimbus-setup.conf"
+    
+    # We know that a fresh installation will have missing things specified in
+    # that conf file.  Any relative path configuratoin in that previous conf
+    # file will be copied over here.  Any absolute path will be noted but not
+    # touched.
+    
+    $CONFIG_SCRIPT $EXTRA_CONFIG_SCRIPT_ARGS --import-prev
+    if [ $? -ne 0 ]; then
+        echo ""
+        echo "Could not import something specified in the old configuration file: $oldnimbusconf"
+        exit 1
+    fi
+    
+    old_vmmdir="$PREVIOUS_NIMBUS_HOME_VALIDATED/services/etc/nimbus/workspace-service/vmm-pools"
+    vmm_cmd="$CONFIG_SCRIPT $EXTRA_CONFIG_SCRIPT_ARGS --import-vmms $old_vmmdir"
+fi
 
+$CONFIG_SCRIPT $EXTRA_CONFIG_SCRIPT_ARGS
 if [ $? -ne 0 ]; then
     echo "Nimbus configuration script failed! You may try running it manually:"
     echo "    $CONFIG_SCRIPT"
@@ -137,7 +183,64 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-
-$NIMBUS_SRC/libexec/install-real.sh  "${@}" 2>&1 | tee -a $NIMBUS_HOME/install.log
+$NIMBUS_SRC/libexec/configure-cumulus.sh  "${@}" 2>&1 | tee -a $NIMBUS_HOME/install.log
 # need PIPESTATUS because tee is not the exit code of interest
-exit $PIPESTATUS
+rc=$PIPESTATUS
+if [ $rc -ne 0 ]; then
+    exit $rc
+fi
+
+if [ "X" != "X$PREVIOUS_NIMBUS_HOME_VALIDATED" ]; then
+    echo ""
+    $CONFIG_SCRIPT $EXTRA_CONFIG_SCRIPT_ARGS --import-cumulusdb
+    if [ $? -ne 0 ]; then
+        echo ""
+        echo "Could not import Cumulus DB from the old configuration file: $oldnimbusconf"
+        exit 1
+    fi
+fi
+
+echo ""
+GUIDEURL=`$NIMBUS_HOME/bin/nimbus-version --guide`
+if [ $? -ne 0 ]; then
+    GUIDEURL="Development mode: no guide url"
+fi
+
+echo ""
+echo "-----------------------------------------------------------------"
+echo " Nimbus installation succeeded!"
+echo "-----------------------------------------------------------------"
+echo ""
+echo "Additional configuration may be necessary, refer to this URL for information:"
+echo ""
+echo "    $GUIDEURL"
+echo ""
+echo "You can start/stop Nimbus services with the nimbusctl command. e.g:"
+echo ""
+echo "    $NIMBUS_HOME/bin/nimbusctl start"
+echo ""
+
+if [ "X" != "X$PREVIOUS_NIMBUS_HOME_VALIDATED" ]; then
+    old_etc_dir=$PREVIOUS_NIMBUS_HOME_VALIDATED/services/etc/nimbus
+    new_etc_dir=$NIMBUS_HOME/services/etc/nimbus
+    echo "-----------------------------------------------------------------"
+    echo " ** Upgrade work still needed **"
+    echo "-----------------------------------------------------------------"
+    echo ""
+    echo "While key settings have been transferred from your old install,"
+    echo "you still need to do a manual confirmation and transfer of"
+    echo "customizations."
+    echo ""
+    echo "Run the following command to look for customizations:"
+    echo ""
+    echo "    diff -u -r $old_etc_dir $new_etc_dir"
+    echo ""
+    echo "After using nimbusctl to start the services, use the following"
+    echo "command to import VMM configurations.  This can only be done "
+    echo "with a running service:"
+    echo ""
+    echo "    $vmm_cmd"
+    echo ""
+fi
+
+exit 0
diff --git a/libexec/create-nimbus-home b/libexec/create-nimbus-home
--- a/libexec/create-nimbus-home
+++ b/libexec/create-nimbus-home
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 CONTAINER_URL="http://www-unix.globus.org/ftppub/gt4/4.0/4.0.8/ws-core/bin/ws-core-4.0.8-bin.tar.gz"
+CONTAINER_URL="https://github.com/downloads/nimbusproject/nimbus/ws-core-4.0.8-bin.tar.gz"
 CONTAINER_TARNAME="ws-core-4.0.8-bin.tar.gz"
 CONTAINER_UNTARREDNAME="ws-core-4.0.8"
 
@@ -37,7 +38,7 @@ echo ""
 if [ ! -f $TMPDIR/$CONTAINER_TARNAME ]; then
     echo "Downloading service container.."
     echo ""
-    wget -c -O $TMPDIR/$CONTAINER_TARNAME $CONTAINER_URL
+    wget --no-check-certificate -c -O $TMPDIR/$CONTAINER_TARNAME $CONTAINER_URL
 
     if [ $? -ne 0 ]; then
     echo ""
@@ -133,9 +134,35 @@ echo "-----------------------------------------------------------------"
 GLOBUS_LOCATION=$CONTAINER_DIR
 export GLOBUS_LOCATION
 
-$NIMBUS_SRC/scripts/all-build-and-install.sh
+$NIMBUS_SRC/scripts/gt/all-build-and-install.sh
 if [ $? -ne 0 ]; then
     echo "Build and install FAILED!"
+    exit 1
+fi
+
+# add in native libraries
+LIBNATIVE="$CONTAINER_DIR/lib-native"
+mkdir -p $LIBNATIVE
+if [ $? -ne 0 ]; then
+    echo "Creation of $LIBNATIVE directory failed"
+    exit 1
+fi
+cp $NIMBUS_SRC/lib/native/* $LIBNATIVE/
+if [ $? -ne 0 ]; then
+    echo "Deployment of native libs failed"
+    exit 1
+fi
+
+# create domain sockets privileged directory
+PRIVILEGED="$NIMBUS_HOME/var/run/privileged"
+mkdir -p $PRIVILEGED
+if [ $? -ne 0 ]; then
+    echo "Creation of privileged domain sockets directory failed: $PRIVILEGED"
+    exit 1
+fi
+chmod 700 $PRIVILEGED
+if [ $? -ne 0 ]; then
+    echo "chmod of privileged domain sockets directory failed: $PRIVILEGED"
     exit 1
 fi
 
